### ISSUE TITLE
Mettre plus en évidence les différents facteurs d'impacts dans la vue détaillée

### ISSUE THREAD

**Issue by clementbrizard** [impactometre/impactometre-front#1]
Quand on arrive sur la vue détaillée d'une catégorie d'impact, il faudrait qu'on voit tout de suite que chaque barre est composée par l'impact du matériel, des transports et du réseau. Là on le voit qu'au survol, donc on peut passer à côté.

**Comment by elouan-lb** [comment]
J'ai ajouté un dégradé pour mieux les différencier, tu peux me dire si ça te semble suffisant ? Merci :)

**Comment by clementbrizard** [comment]
Ca fonctionne, merci Elouan :) Idéalement, je pense qu'il faudrait faire un truc dynamique, indépendant du nombre de catégories d'impact. Comme ça si un jour il y a un impactomètre pour le streaming musical par exemple, et qu'il y a 4 ou 5 catégories d'impact, le code marchera quand-même.
