### ISSUE TITLE
 Ca crash quand un champ vaut rien

### ISSUE THREAD

**Issue by clementbrizard** [impactometre/impactometre-front#2]
A l'usage, je me suis retrouvé avec un champ qui valait rien, impossible alors de lancer les calculs. Je m'en suis sorti en remettant ce champ à 0.

Il faudrait que dès qu'on sort de l'édition d'un champ, si on a laissé aucune valeur, on remette 0 dedans. Ou alors, et ce serait sans-doute mieux, ajouter une valeur par défaut aux inputs.

**Comment by elouan-lb** [comment]
Je pense avoir réglé le problème (voir 1241c84), en utilisant le `@blur` et la valeur du champ par défaut.

**Comment by clementbrizard** [comment]
Ca fonctionne merci :)

Pour les prochaines, ne fermons pas les issues avant d'avoir validé que ça marche, ça permet aussi d'avoir un meilleur suivi. Idéalement créons une PR par issue, on review la PR, on fait éventuellement des changements, on merge, et là on ferme l'issue.

**Comment by elouan-lb** [comment]
Yes ça me semble être une bonne pratique :)
