### ISSUE TITLE
Changer les valeurs maximales et par défaut afin d'être plus proche de la réalité

### ISSUE THREAD

**Issue by auberanger** [impactometre/impactometre-front#21]
Nouvelles valeurs par défaut  :
- le nombre minimum de participants à une réunion est 2 (on ne fait pas de réunions tout seul a priori !), il serait logique de mettre ça par défaut plutôt que 1 ;
- la durée d'une réunion n'est jamais de 1 minute, peut-être qu'on pourrait mettre 60 par défaut pour que ça ait plus de sens ;
- le nombre d'instances d'un logiciel a été mis par défaut à 2 dans la PR #4 

Suite à des retours utilisateur, nous changeons aussi les valeurs maximales pour pouvoir prendre en compte tous les scénarios possibles. Voici les valeurs maximales passées à 99 999 : 
* durée (avant : 999)
* nombre de participants (avant : 999)
* nombre d'instances (avant : 999)
* nombre de chaque composants matériels (avant : 99)
* distance des trajets (avant : 9999)

**Comment by ValLG** [comment]
@YacineBaouch Nous avons changé les valeurs par défaut et maximales des scénarios. Nous voulions avoir votre avis sur ces modifs. Qu'en pensez-vous ?

**Comment by YacineBaouch** [comment]
Je pense que les nouvelles valeurs maximales sont bonnes (même si une réunion de 2 mois est peu probable).
Je pense que c'est aussi pertinent de mettre par défaut 2 personnes mais il sera toujours possible de descendre à un 1 ? On peut imaginer un utilisateur qui déforme l'impactomètre pour d'autres évaluations (comparer des trajets de voiture etc...).
C'est aussi plus logique de commencer à 60 minutes. Par contre, le pas peut-il être de 5 min ?

**Comment by clementbrizard** [comment]
> Je pense que les nouvelles valeurs maximales sont bonnes (même si une réunion de 2 mois est peu probable).
> Je pense que c'est aussi pertinent de mettre par défaut 2 personnes mais il sera toujours possible de descendre à un 1 ? On peut imaginer un utilisateur qui déforme l'impactomètre pour d'autres évaluations (comparer des trajets de voiture etc...).
> C'est aussi plus logique de commencer à 60 minutes. Par contre, le pas peut-il être de 5 min ?

**Comment by clementbrizard** [comment]
Il sera oui toujours possible de descendre à 1.
Pour le pas de 5, nous y avons pensé en effet, mais nous pensions nous en occuper plus tard. Actuellement si on change le pas, ça va être le même pour tous les champs, donc ça donnerait aussi un pas de 5 pour la distance par exemple, alors qu'on aimerait sans-doute un pas plus élevé. Donc gérer ces différents pas nécessitera a priori un travail spécifique, je crée une issue : #29.
