### ISSUE TITLE
Ajouter un champ pour le nombre d'instances du logiciel

### ISSUE THREAD

**Issue by clementbrizard** [impactometre/impactometre-front#4]
Pour le calcul de l'impact du logiciel, il faut connaître le nombre d'instances du logiciel (cad le nombre d'ordis sur lesquels le logiciel tourne). Par exemple, il peut y avoir 4 participants à la réunion, mais seulement 2 instances, si les gens sont à 2 derrière le même ordi. C'est pareil si on est dans une salle de visio, il peut y avoir x personnes, il y a une seule instance partagée.

Donc il faudrait ajouter un champ "Nb d'instances du logiciel", avec sans-doute un tooltip pour expliquer ce qu'on entend par "instance".

- [x] Rajouter un champ dans le formulaire du scénario
- [x] Rajouter le champ dans l'export de résultats
- [x] Renvoyer dans la Payload la valeur de ce nouveau champ à la place du nb d'utilisateurs
- [x] Faire apparaître le champ lorsqu'on sélectionne autre chose que "Aucune" dans le champ "Visio"
- [x] Faire disparaître et réinitialiser le champ lorsqu'on sélectionne "Aucune" dans le champ "Visio"
- [x] Valider un nom de champ suffisamment clair et un bel émoji ;)
- [x] Ajouter une infobulle (?) pour expliquer le sens du champ "Nb d'instances du logiciel/nombre de points de réunion"

**Comment by auberanger** [comment]
- [ ] Ajouter une infobulle (?) pour expliquer le sens du champ "nombre de points de réunion"
